test sonar

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,7 +68,12 @@ jobs:
       - name: Check Quality Gate (Public)
         run: |
           response=$(wget -q -O - "http://data.tocalivros.com:9000/api/qualitygates/project_status?projectKey=mania-public&token=sqp_95245917aa19a69fc343dc5f854d846e9c13a4db")
-          echo "$response"
+          status=$(echo "$response" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $status"
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed."
+            exit 1
+          fi
 
       - name: SonarQube Scan (Partner)
         uses: SonarSource/sonarqube-scan-action@master
@@ -87,7 +92,12 @@ jobs:
       - name: Check Quality Gate (Partner)
         run: |
           response=$(wget -q -O - "http://data.tocalivros.com:9000/api/qualitygates/project_status?projectKey=mania-partner&token=sqp_3444075491e5fb1d429c67e368f4a85298c8268a")
-          echo "$response"
+          status=$(echo "$response" | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $status"
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed."
+            exit 1
+          fi
 
       - name: Run Lint (Partner)
         run: pnpm run lint:partner
